# ---
- name: devops
  hosts: cicd
  remote_user: alexey
  
  vars: 
    test: test.html
    index_path: /docker/jenkins
    become: true
    gather_facts: false
  
  tasks:
  # - name: upd pkg list
  #   community.general.apk:
  #     name: nginx
  #     update_cache: true
      
  - name: create dir
    ansible.builtin.file:
      path: "{{ index_path }}/"
      state: directory
      # owner: docker
      # group: docker
  - name: create dir
    ansible.builtin.file:
      path: "{{ index_path }}/nexus_data/"
      state: directory
      # owner: docker
      # group: docker

  - name: create dir
    ansible.builtin.file:
      path: "{{ index_path }}/jenkins_home/"
      state: directory
      # owner: docker
      # group: docker 

  - name: cp file docker-compose
    ansible.builtin.copy:
      src: /home/alexey/DevOps/ansible_lesson/ini_form/devops_course/jenkins/docker-compose.yml
      dest: "{{ index_path }}/"
  
  - name: start docker service
    ansible.builtin.service:
      name: docker
      state: started
    
  - name: start_container
    community.docker.docker_compose:
      project_src: "{{ index_path }}"
      # files:
      # - docker-compose.yml
      build: true
    register: output

  - name: Show results
    ansible.builtin.debug:
      var: output


  # - name: Start flask project with inline definition
  #   community.docker.docker_compose:
  #     project_name: jenkins
  #     definition:
  #       version: '3.8'
  #       services:
  #         jenkins:
  #            image: jenkins/jenkins:lts-jdk11
  #               ports:
  #                 - "8080:8080"
  #                 - "50000:50000"
  #               volumes:
  #                 - "jenkins_home:/var/jenkins_home"
  #                 - "/var/run/docker.sock:/var/run/docker.sock"
  #               user: root
  #               networks:
  #                 - cicd_network
              # nexus:
              #   image: sonatype/nexus3
              #   ports:
              #     - "8081:8081"
              #     - "8083:8083"
              #   volumes:
              #     - "nexus_data:/nexus-data"
              #   networks:
              #     - cicd_network
            # volumes:
            #   jenkins_home:
            #     external: true
            #     name: jenkins_home
            #   nexus_data:
            #     external: true
            #     name: nexus_data
            # networks:
            #     cicd_network:
            #         driver: bridge
    # register: output

  # - name: Show results
  #   ansible.builtin.debug:
  #     var: output